// Mocks generated by Mockito 5.4.6 from annotations
// in bangumi_today/test/data/repositories/bangumi_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bangumi_today/data/datasources/bangumi_remote_data_source.dart'
    as _i3;
import 'package:bangumi_today/models/app/response.dart' as _i2;
import 'package:bangumi_today/models/bangumi/bangumi_enum.dart' as _i6;
import 'package:bangumi_today/models/bangumi/bangumi_model.dart' as _i7;
import 'package:bangumi_today/models/bangumi/request_subject.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBTResponse_0<T> extends _i1.SmartFake implements _i2.BTResponse<T> {
  _FakeBTResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BTBangumiRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBTBangumiRemoteDataSource extends _i1.Mock
    implements _i3.BTBangumiRemoteDataSource {
  MockBTBangumiRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BTResponse<List<_i5.BangumiCalendarRespData>>> getToday() =>
      (super.noSuchMethod(
            Invocation.method(#getToday, []),
            returnValue:
                _i4.Future<
                  _i2.BTResponse<List<_i5.BangumiCalendarRespData>>
                >.value(
                  _FakeBTResponse_0<List<_i5.BangumiCalendarRespData>>(
                    this,
                    Invocation.method(#getToday, []),
                  ),
                ),
          )
          as _i4.Future<_i2.BTResponse<List<_i5.BangumiCalendarRespData>>>);

  @override
  _i4.Future<dynamic> searchSubjects(
    String? keyword, {
    String? sort,
    int? offset,
    int? limit,
    List<_i6.BangumiSubjectType>? type,
    List<String>? tag,
    List<String>? airdate,
    List<String>? rating,
    List<String>? rank,
    bool? nsfw,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchSubjects,
              [keyword],
              {
                #sort: sort,
                #offset: offset,
                #limit: limit,
                #type: type,
                #tag: tag,
                #airdate: airdate,
                #rating: rating,
                #rank: rank,
                #nsfw: nsfw,
              },
            ),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<_i2.BTResponse<_i7.BangumiSubject>> getSubjectDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectDetail, [id]),
            returnValue: _i4.Future<_i2.BTResponse<_i7.BangumiSubject>>.value(
              _FakeBTResponse_0<_i7.BangumiSubject>(
                this,
                Invocation.method(#getSubjectDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.BTResponse<_i7.BangumiSubject>>);

  @override
  _i4.Future<_i2.BTResponse<List<_i7.BangumiSubjectRelation>>>
  getSubjectRelations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectRelations, [id]),
            returnValue:
                _i4.Future<
                  _i2.BTResponse<List<_i7.BangumiSubjectRelation>>
                >.value(
                  _FakeBTResponse_0<List<_i7.BangumiSubjectRelation>>(
                    this,
                    Invocation.method(#getSubjectRelations, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.BTResponse<List<_i7.BangumiSubjectRelation>>>);

  @override
  _i4.Future<_i2.BTResponse<_i7.BangumiPageT<_i7.BangumiEpisode>>>
  getEpisodeList(
    int? id, {
    _i6.BangumiLegacyEpisodeType? type,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEpisodeList,
              [id],
              {#type: type, #limit: limit, #offset: offset},
            ),
            returnValue:
                _i4.Future<
                  _i2.BTResponse<_i7.BangumiPageT<_i7.BangumiEpisode>>
                >.value(
                  _FakeBTResponse_0<_i7.BangumiPageT<_i7.BangumiEpisode>>(
                    this,
                    Invocation.method(
                      #getEpisodeList,
                      [id],
                      {#type: type, #limit: limit, #offset: offset},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.BTResponse<_i7.BangumiPageT<_i7.BangumiEpisode>>>);

  @override
  _i4.Future<_i2.BTResponse<_i7.BangumiUser>> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue: _i4.Future<_i2.BTResponse<_i7.BangumiUser>>.value(
              _FakeBTResponse_0<_i7.BangumiUser>(
                this,
                Invocation.method(#getUserInfo, []),
              ),
            ),
          )
          as _i4.Future<_i2.BTResponse<_i7.BangumiUser>>);

  @override
  _i4.Future<_i2.BTResponse<_i7.BangumiPageT<_i7.BangumiUserSubjectCollection>>>
  getCollectionSubjects({
    String? username,
    _i6.BangumiSubjectType? subjectType,
    _i6.BangumiCollectionType? collectionType,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCollectionSubjects, [], {
              #username: username,
              #subjectType: subjectType,
              #collectionType: collectionType,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i4.Future<
                  _i2.BTResponse<
                    _i7.BangumiPageT<_i7.BangumiUserSubjectCollection>
                  >
                >.value(
                  _FakeBTResponse_0<
                    _i7.BangumiPageT<_i7.BangumiUserSubjectCollection>
                  >(
                    this,
                    Invocation.method(#getCollectionSubjects, [], {
                      #username: username,
                      #subjectType: subjectType,
                      #collectionType: collectionType,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.BTResponse<_i7.BangumiPageT<_i7.BangumiUserSubjectCollection>>
          >);

  @override
  _i4.Future<_i2.BTResponse<_i7.BangumiUserSubjectCollection>>
  getCollectionSubject(String? username, int? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollectionSubject, [username, subjectId]),
            returnValue:
                _i4.Future<
                  _i2.BTResponse<_i7.BangumiUserSubjectCollection>
                >.value(
                  _FakeBTResponse_0<_i7.BangumiUserSubjectCollection>(
                    this,
                    Invocation.method(#getCollectionSubject, [
                      username,
                      subjectId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.BTResponse<_i7.BangumiUserSubjectCollection>>);

  @override
  _i4.Future<_i2.BTResponse<void>> addCollectionSubject(int? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#addCollectionSubject, [subjectId]),
            returnValue: _i4.Future<_i2.BTResponse<void>>.value(
              _FakeBTResponse_0<void>(
                this,
                Invocation.method(#addCollectionSubject, [subjectId]),
              ),
            ),
          )
          as _i4.Future<_i2.BTResponse<void>>);

  @override
  _i4.Future<_i2.BTResponse<void>> updateCollectionSubject(
    int? subjectId, {
    _i6.BangumiCollectionType? type,
    int? rate,
    int? ep,
    int? vol,
    String? comment,
    bool? private,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateCollectionSubject,
              [subjectId],
              {
                #type: type,
                #rate: rate,
                #ep: ep,
                #vol: vol,
                #comment: comment,
                #private: private,
                #tags: tags,
              },
            ),
            returnValue: _i4.Future<_i2.BTResponse<void>>.value(
              _FakeBTResponse_0<void>(
                this,
                Invocation.method(
                  #updateCollectionSubject,
                  [subjectId],
                  {
                    #type: type,
                    #rate: rate,
                    #ep: ep,
                    #vol: vol,
                    #comment: comment,
                    #private: private,
                    #tags: tags,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.BTResponse<void>>);

  @override
  _i4.Future<_i2.BTResponse<_i7.BangumiPageT<_i7.BangumiUserEpisodeCollection>>>
  getCollectionEpisodes(
    int? subjectId, {
    int? offset,
    int? limit,
    _i6.BangumiLegacyEpisodeType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCollectionEpisodes,
              [subjectId],
              {#offset: offset, #limit: limit, #type: type},
            ),
            returnValue:
                _i4.Future<
                  _i2.BTResponse<
                    _i7.BangumiPageT<_i7.BangumiUserEpisodeCollection>
                  >
                >.value(
                  _FakeBTResponse_0<
                    _i7.BangumiPageT<_i7.BangumiUserEpisodeCollection>
                  >(
                    this,
                    Invocation.method(
                      #getCollectionEpisodes,
                      [subjectId],
                      {#offset: offset, #limit: limit, #type: type},
                    ),
                  ),
                ),
          )
          as _i4.Future<
            _i2.BTResponse<_i7.BangumiPageT<_i7.BangumiUserEpisodeCollection>>
          >);

  @override
  _i4.Future<_i2.BTResponse<_i7.BangumiUserEpisodeCollection>>
  getCollectionEpisode(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getCollectionEpisode, [episodeId]),
            returnValue:
                _i4.Future<
                  _i2.BTResponse<_i7.BangumiUserEpisodeCollection>
                >.value(
                  _FakeBTResponse_0<_i7.BangumiUserEpisodeCollection>(
                    this,
                    Invocation.method(#getCollectionEpisode, [episodeId]),
                  ),
                ),
          )
          as _i4.Future<_i2.BTResponse<_i7.BangumiUserEpisodeCollection>>);

  @override
  _i4.Future<_i2.BTResponse<void>> updateCollectionEpisode({
    required _i6.BangumiEpisodeCollectionType? type,
    required int? episode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCollectionEpisode, [], {
              #type: type,
              #episode: episode,
            }),
            returnValue: _i4.Future<_i2.BTResponse<void>>.value(
              _FakeBTResponse_0<void>(
                this,
                Invocation.method(#updateCollectionEpisode, [], {
                  #type: type,
                  #episode: episode,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.BTResponse<void>>);
}
