# Compiles the frame conversion kernels with the pinned Windows SDK shader
# compiler and embeds the DXBC bytecode in a generated header. Run through
# `cmake -P` from the inference target, never as a standalone script.
foreach(_required FXC SHADER_SOURCE OUTPUT_HEADER GENERATED_DIR)
  if(NOT DEFINED ${_required})
    message(FATAL_ERROR "embed_frame_shaders.cmake requires -D${_required}=<value>")
  endif()
endforeach()

set(_entries
  "YuvToPlanarRgb:kFrameShaderYuvToPlanarRgb"
  "PlanarRgbToLuma:kFrameShaderPlanarRgbToLuma"
  "PlanarRgbToChroma:kFrameShaderPlanarRgbToChroma")

get_filename_component(_shader_name "${SHADER_SOURCE}" NAME)
set(_header "// Generated by cmake/embed_frame_shaders.cmake from ${_shader_name}.\n")
string(APPEND _header "// Edit the HLSL source, never this file.\n")
string(APPEND _header "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n")
string(APPEND _header "namespace bangumi::inference {\n\n")
string(APPEND _header "struct EmbeddedShader {\n  const uint8_t* data;\n  size_t size;\n};\n\n")

foreach(_entry IN LISTS _entries)
  string(REPLACE ":" ";" _parts "${_entry}")
  list(GET _parts 0 _function)
  list(GET _parts 1 _symbol)
  set(_object "${GENERATED_DIR}/${_function}.cso")
  execute_process(
    COMMAND "${FXC}" /nologo /T cs_5_0 /E ${_function} /O3 /WX "/Fo${_object}" "${SHADER_SOURCE}"
    RESULT_VARIABLE _result
    OUTPUT_VARIABLE _stdout
    ERROR_VARIABLE _stderr)
  if(NOT _result EQUAL 0)
    message(FATAL_ERROR "fxc failed for ${_function}:\n${_stdout}\n${_stderr}")
  endif()
  file(READ "${_object}" _hex HEX)
  string(LENGTH "${_hex}" _hex_length)
  math(EXPR _byte_count "${_hex_length} / 2")
  string(APPEND _header "// ${_function}: cs_5_0, ${_byte_count} bytes.\n")
  string(APPEND _header "inline constexpr uint8_t ${_symbol}Bytecode[] = {\n")
  set(_line "  ")
  set(_index 0)
  while(_index LESS _byte_count)
    math(EXPR _offset "${_index} * 2")
    string(SUBSTRING "${_hex}" ${_offset} 2 _byte)
    string(APPEND _line "0x${_byte},")
    math(EXPR _index "${_index} + 1")
    math(EXPR _column "${_index} % 16")
    if(_column EQUAL 0)
      string(APPEND _header "${_line}\n")
      set(_line "  ")
    else()
      string(APPEND _line " ")
    endif()
  endwhile()
  if(NOT _line STREQUAL "  ")
    string(APPEND _header "${_line}\n")
  endif()
  string(APPEND _header "};\n")
  string(APPEND _header "inline constexpr EmbeddedShader ${_symbol}{${_symbol}Bytecode, sizeof(${_symbol}Bytecode)};\n\n")
endforeach()

string(APPEND _header "}  // namespace bangumi::inference\n")
file(WRITE "${OUTPUT_HEADER}" "${_header}")
