name: Build MicrosoftStore Version

on: workflow_dispatch

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    env:
      BANGUMI_APP_ID: ${{ secrets.BANGUMI_APP_ID }}
      BANGUMI_APP_SECRET: ${{ secrets.BANGUMI_APP_SECRET }}
    steps:

      - name: 签出仓库
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          ref: master

      - name: 初始化 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          architecture: x64

      - name: 检查环境
        run: flutter doctor

      - name: 拉取依赖
        run: flutter pub get

      - name: 写入 .env
        shell: pwsh
        run: |
          New-Item -Path . -Name .env -ItemType File -Force
          Add-Content -Path .env -Value "BANGUMI_APP_ID=${env:BANGUMI_APP_ID}"
          Add-Content -Path .env -Value "BANGUMI_APP_SECRET=${env:BANGUMI_APP_SECRET}"

      - name: 构建项目
        run: flutter build windows

      - name: 构建 MSIX
        run: dart run msix:create --publisher CN=5FE33156-C3CE-4E71-A036-81BAA99521CB --store true

      - name: 上传 MSIX
        uses: actions/upload-artifact@v4
        with:
          name: BangumiToday(Store).msix
          path: build/windows/x64/runner/Release/BangumiToday.msix
