name: Build MicrosoftStore Version

on: workflow_dispatch

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:

      - name: 签出仓库
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          ref: master

      - name: 初始化 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          architecture: x64

      - name: 检查环境
        run: flutter doctor

      - name: 拉取依赖
        run: flutter pub get

      - name: 构建项目
        run: flutter build windows

      - name: 构建 MSIX
        if: env.CERTIFICATE != ''
        run: dart run msix:create --publisher CN=5FE33156-C3CE-4E71-A036-81BAA99521CB --store true

      - name: 上传 MSIX
        if: env.CERTIFICATE != ''
        uses: actions/upload-artifact@v4
        with:
          name: BangumiToday.msix(Store)
          path: build/windows/x64/runner/Release/BangumiToday.msix
